---
name: fvtt-release

on:
  push:
    tags:
      - "*" # triggers on all new tags

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: create module archive
        run: |
          sed -i "s|versionNumberToBeInsertedByAutomation|${{ github.ref_name }}|g" ./module.json;
          zip -r ./module.zip ./sheet.js ./module.json ./README.md;

      - name: create release
        uses: ncipollo/release-action@v1
        with:
          name: ${{ github.ref_name }}
          draft: false
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: ./module.json, ./module.zip
          tag: ${{ github.ref_name }}
          generateReleaseNotes: true

      - name: create foundry release
        run: |
          curl \
            -X POST \
            -H "Authorization: ${{ secrets.FVTT_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d '{
              "id": "${{ github.event.repository.name }}",
              "dry-run": true,
              "release": {
                "version": "${{ github.ref_name }}",
                "manifest": "${{ github.server_url }}/${{ github.repository }}/releases/download/${{ github.ref_name }}/module.json",
                "notes": "${{ github.server_url }}/${{ github.repository }}/commits/${{ github.ref_name }}",
                "compatibility": {
                  "minimum": "13",
                  "verified": "13",
                  "maximum": "13"
                }
              }
            }' \
            https://foundryvtt.com/_api/packages/release_version/
